metadata:
  name: bs-${project.artifactId}
data:
  application.properties: |
    logging.level.qslv=DEBUG
    qslv.aitid=12345
    spring.datasource.url=jdbc:postgresql://cockroach.quick-silver.svc:26257/deposits?sslmode=disable
    spring.datasource.username=root
    qslv.commit-reservation-url=http://qslv-transaction-rest-quick-silver.192.168.64.3.nip.io/CommitReservation
    qslv.rest-connect-timeout=500
    qslv.rest-connection-request-timeout=500
    qslv.rest-attempts=3
    qslv.rest-backoff-delay=100
    qslv.rest-backoff-delay-max=500
    qslv.rest-timeout=500
    qslv.kafka-commit-reply-queue=commit.fulfillment.reply.queue
    qslv.kafka-commit-request-queue=commit.fulfillment.request.queue
    qslv.kafka-consumer-properties-path=/deployments/config/kafka-consumer/kafka.properties
    qslv.kafka-producer-properties-path=/deployments/config/kafka-producer/kafka.properties
    qslv.kafka-timeout=1000
    management.endpoint.health.show-details=always
    management.endpoint.health.show-components=always
    